# Generated by Django 5.2.16 on 2026-07-30 17:06

from django.db import migrations, models


def backfill_currency_from_owner(apps, schema_editor):
    """See expenses.migrations.0004's backfill — same best-effort reasoning,
    just for the mirrored `currency` snapshot on ServiceRecord (#40)."""
    ServiceRecord = apps.get_model("services", "ServiceRecord")
    User = apps.get_model("accounts", "User")
    for user_id, currency in User.objects.exclude(currency="").values_list("id", "currency"):
        ServiceRecord.objects.filter(car__owner_id=user_id).update(currency=currency)


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        ("accounts", "0009_user_country_user_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerecord",
            name="currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.RunPython(backfill_currency_from_owner, migrations.RunPython.noop),
    ]
