# Generated by Django 5.2.16 on 2026-08-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_servicerecord_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerecord",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("minor_service", "Minor Service"),
                    ("major_service", "Major Service"),
                    ("oil_change", "Oil Change"),
                    ("oil_filter", "Oil Filter"),
                    ("air_filter", "Engine Air Filter"),
                    ("cabin_filter", "Cabin/Pollen Filter"),
                    ("fuel_filter", "Fuel Filter"),
                    ("spark_plugs", "Spark Plugs"),
                    ("timing_belt", "Timing Belt/Chain"),
                    ("drive_belt", "Drive/Serpentine Belt"),
                    ("coolant", "Coolant/Antifreeze"),
                    ("brake_fluid", "Brake Fluid"),
                    ("power_steering_fluid", "Power Steering Fluid"),
                    ("washer_fluid", "Washer Fluid"),
                    ("battery", "Battery"),
                    ("brakes", "Brakes"),
                    ("suspension", "Suspension"),
                    ("wheel_alignment", "Wheel Alignment"),
                    ("wheel_balancing", "Wheel Balancing"),
                    ("tyres", "Tyres"),
                    ("exhaust", "Exhaust"),
                    ("other", "Other"),
                ],
                default="minor_service",
                max_length=30,
            ),
        ),
    ]
