# Generated by Django 5.2.16 on 2026-07-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_car_photo_odometer_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="photo",
        ),
        migrations.AddField(
            model_name="car",
            name="photo_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
