# Generated by Django 5.2.16 on 2026-07-14 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_car_photo_odometer_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('catalog_key', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('documentation', 'Documents'), ('other', 'Other')], default='other', max_length=20)),
                ('is_essential', models.BooleanField(default=False)),
                ('tracking_method', models.CharField(choices=[('date_and_mileage', 'By date & mileage'), ('date', 'By date'), ('mileage', 'By mileage')], default='date_and_mileage', max_length=20)),
                ('interval_km', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_months', models.PositiveIntegerField(blank=True, null=True)),
                ('baseline_odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('baseline_date', models.DateField(blank=True, null=True)),
                ('next_due_odometer_km', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('next_due_date', models.DateField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='cars.car')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
