# Generated by Django 5.2.16 on 2026-07-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deletion_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
