# Generated by Django 5.2.16 on 2026-07-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_deletion_reminder_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deletion_reminder_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mileage_reminder_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
