# Generated by Django 5.2.16 on 2026-07-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_reminder_claim_leases"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verify_reminder_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verify_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
