# Generated by Django 5.2.16 on 2026-07-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_verify_reminder_queued_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Prefer not to say"),
                    ("AT", "Austria"),
                    ("AU", "Australia"),
                    ("AE", "United Arab Emirates"),
                    ("BE", "Belgium"),
                    ("CA", "Canada"),
                    ("DE", "Germany"),
                    ("EG", "Egypt"),
                    ("ES", "Spain"),
                    ("FI", "Finland"),
                    ("FR", "France"),
                    ("GB", "United Kingdom"),
                    ("GH", "Ghana"),
                    ("IE", "Ireland"),
                    ("IN", "India"),
                    ("IT", "Italy"),
                    ("KE", "Kenya"),
                    ("NG", "Nigeria"),
                    ("NL", "Netherlands"),
                    ("PT", "Portugal"),
                    ("RW", "Rwanda"),
                    ("TZ", "Tanzania"),
                    ("UG", "Uganda"),
                    ("US", "United States"),
                    ("ZA", "South Africa"),
                ],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not set — show plain amounts"),
                    ("UGX", "Ugandan Shilling (UGX)"),
                    ("KES", "Kenyan Shilling (KES)"),
                    ("TZS", "Tanzanian Shilling (TZS)"),
                    ("RWF", "Rwandan Franc (RWF)"),
                    ("NGN", "Nigerian Naira (NGN)"),
                    ("GHS", "Ghanaian Cedi (GHS)"),
                    ("ZAR", "South African Rand (ZAR)"),
                    ("EGP", "Egyptian Pound (EGP)"),
                    ("USD", "US Dollar (USD)"),
                    ("GBP", "British Pound (GBP)"),
                    ("EUR", "Euro (EUR)"),
                    ("INR", "Indian Rupee (INR)"),
                    ("AED", "UAE Dirham (AED)"),
                    ("CAD", "Canadian Dollar (CAD)"),
                    ("AUD", "Australian Dollar (AUD)"),
                ],
                max_length=3,
            ),
        ),
    ]
