# Generated by Django 5.2.16 on 2026-07-30 17:06

from django.db import migrations, models


def backfill_currency_from_owner(apps, schema_editor):
    """
    Pre-#40 expenses predate the `currency` field entirely. There's no
    record of what currency they were actually logged in, so this uses the
    owner's *current* currency as a best-effort stand-in — the same
    best-available-signal approach #40 already takes for country/currency
    backfill in general. Left blank (falls back to an unconverted, bare
    amount) for owners who still have no currency set.
    """
    Expense = apps.get_model("expenses", "Expense")
    User = apps.get_model("accounts", "User")
    # F() can't reference a joined field in update(), so this backfills one
    # owner's currency at a time rather than in a single cross-table query.
    for user_id, currency in User.objects.exclude(currency="").values_list("id", "currency"):
        Expense.objects.filter(car__owner_id=user_id).update(currency=currency)


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_monthlyexpensereportdelivery"),
        ("accounts", "0009_user_country_user_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("currency", models.CharField(max_length=3)),
                ("rate_to_usd", models.DecimalField(decimal_places=10, max_digits=20)),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(fields=("date", "currency"), name="unique_exchange_rate_per_day")
                ],
            },
        ),
        migrations.RunPython(backfill_currency_from_owner, migrations.RunPython.noop),
    ]
