# Generated by Django 5.2.16 on 2026-07-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_expense_currency_exchangerate"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="exchangerate",
            index=models.Index(fields=["currency", "-date"], name="exchangerate_currency_date_idx"),
        ),
    ]
