# Generated by Django 5.2.16 on 2026-08-18 21:51

import functools
import inspections.models
import utils.Uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0002_report_type_allowlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="report",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=inspections.models.inspection_report_path,
                validators=[
                    utils.Uploads.validate_upload_type,
                    functools.partial(utils.Uploads.validate_upload_size, *(), **{"max_size_mb": 10}),
                ],
            ),
        ),
    ]
